// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbglhzlwrapstxmjcefd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpiZ2xoemx3cmFwc3R4bWpjZWZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NDA0MTcsImV4cCI6MjA2NjUxNjQxN30.rxIehgAFFjJ9PXs_cm9KbccOGkDxE2boIkXl5kUseQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);