name: Trigger Deployment on VPS

on:
  push:
    branches:
      - main  # ou la branche de ton choix

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deploy script on VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 109.234.167.58
          username: beha7263
          key: ${{ secrets.key_o2switcher }}
          port: 22
          script: |
            cd /root/chorbane-espoir-web-portal
            git pull origin main
            npm install
            npm run build
            sudo cp -r dist/* /var/www/html/
